highlighter: rouge
markdown: rdiscount
rdiscount:
extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
host: 0.0.0.0
port: 42222
safe: true
url: http://danbunker.org
author: Dan Bunker

# edit this section with your information
# for a normal use at the base of the server change it to "/"
baseurl: 
title: Dan Bunker - Resume
name: Dan Bunker
email: dbunked@gmail.com
email_full: mailto:dbunked@gmail.com
website: danbunker.org
website_full: http://danbunker.org
github: ejsuncy
twitter: ejsuncy
tel: 385-345-1099
tel_full: 385-345-1099
google_maps: 'https://goo.gl/maps/mCc6RA7Bkds'
address: '3900 Adobe Way'
postcode: 84043
city: Lehi, UT
country: US
google_analytics: UA-47021101-8

# needed for travis-ci build
exclude: [vendor, build.sh]
